apiVersion: apps/v1
kind: Deployment
metadata:
  name: vet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vet-service
  template:
    metadata:
      labels:
        app: vet-service
    spec:
      containers:
        - name: vet-service
          image: gcr.io/petcare-cia3-demo/vet-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: FIREBASE_PROJECT_ID
              value: "petcare-cia3-demo"
            - name: GOOGLE_CLOUD_PROJECT
              value: "petcare-cia3-demo"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vet-service
spec:
  selector:
    app: vet-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
